replicaCount: 2

image:
  repository: splegi/flask-hello # твой Docker Hub репо
  pullPolicy: IfNotPresent
  tag: "39"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  host: flask.local
  annotations: {}
  tls: false
  tlsSecretName: flask-tls

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

vpa:
  enabled: true
  updateMode: Auto
  minAllowed:
    cpu: "100m"
    memory: "128Mi"
  maxAllowed:
    cpu: "1"
    memory: "512Mi"
