{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: flask-hello-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: flask-deploy
    minReplicas: {{ .Values.hpa.minReplicas }}
    maxReplicas: {{ .Values.hpa.maxReplicas }}
    metrics:
        - type: Resource
          resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
    behavior:
        scaleUp:
            stabilizationWindowSeconds: 0
            tolerance: 0.05
            policies:
                - type: Percent
                  value: 100
                  periodSeconds: 15
        scaleDown:
            stabilizationWindowSeconds: 300
            tolerance: 0.15
            policies:
                - type: Percent
                  value: 50
                  periodSeconds: 30
{{- end }}
