{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flask-hello.fullname" . }}
  labels:
    {{- include "flask-hello.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.ingress.host | default "flask.local" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-flask
                port:
                  number: 80
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | default "flask.local" }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
{{- end }}


