apiVersion: v1
kind: Service
metadata:
    name: service-flask
spec:
    type: {{ .Values.service.type }}
    selector:
        app: flask-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5000